name: continuous-integration

on:
  push:
    branches: [master]
    tags:
      - 'v*'
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - uses: pre-commit/action@v2.0.3

  pre-commit-hook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install pre-commit
      run: pip install pre-commit
    # Run pre-commit with try-repo to test the local version of the pre-commit hook
    # because we cannot initialize a local repo easily with the normal configuration file.
    # See https://pre-commit.com/#developing-hooks-interactively for details.
    - name: run pre-commit
      run: pre-commit try-repo -v -a --show-diff-on-failure .

  # for speed, we run a test matrix against only the tests that do not require TeX,
  # then test-with-cov for all tests, for a single environment

  test-with-cov:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -e .[testing]

    - name: Install Headless Chrome dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -yq $(cat .github/workflows/pyppeteer_reqs.txt)

    - name: Install latex dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y   \
          texlive                 \
          texlive-xetex           \
          texlive-latex-extra     \
          texlive-fonts-extra     \
          fonts-freefont-otf      \
          latexmk                 \
          xindy

    - name: Run pytest
      run: |
        pytest --durations=10 --cov=jupyter_book --cov-report=xml --cov-report=term-missing
        coverage xml
      # for some reason the tests/conftest.py::check_nbs fixture breaks pytest-cov's cov-report outputting
      # this is why we run `coverage xml` afterwards (required by codecov)

    - name: Upload to Codecov
      if: github.repository == 'executablebooks/jupyter-book'
      uses: codecov/codecov-action@v2.1.0
      with:
        name: ebp-jupyter-book-pytests-py3.8
        flags: pytests
        file: ./coverage.xml
        fail_ci_if_error: true

  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
        sphinx: [">=3,<4", ">=4,<5"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install "sphinx${{ matrix.sphinx }}"
        pip install -e .[testing]

    - name: Install Headless Chrome dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -yq $(cat .github/workflows/pyppeteer_reqs.txt)

    - name: Run pytest
      run: pytest --durations=10 -m 'not requires_tex'

  windows:

    name: Tests on Windows
    runs-on: windows-latest
    strategy:
      matrix:
        # Using the default python in the Windows 2022 github actions runner
        # ref: https://github.com/actions/virtual-environments/issues/4856
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
    - uses: actions/cache@v3
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.python-version }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install --upgrade-strategy eager -e .[testing]
    - name: Run pytest
      run: pytest --durations=10 -m 'not requires_chrome and not requires_tex' --jb-tempdir local_path

  # Build the book on OSX to make sure that building the docs works there too
  build-book-osx:
    name: Build docs on OSX
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
    - uses: actions/cache@v3
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.python-version }}-pip-
    # We install libmagic to avoid a flaky Fonts error with matplotlib
    # ref: https://stackoverflow.com/questions/62279920/python-macos-error-unable-to-revert-mtime-library-fonts
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install --upgrade-strategy eager -e .[sphinx]
        brew install libmagic

    - name: Build the book
      run: |
        jb build -W -n --keep-going --builder html docs/

  publish:

    name: Publish to PyPi
    needs: [pre-commit, tests, test-with-cov, build-book-osx]
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install flit
        run: |
          pip install flit~=3.6

      - name: Build and publish
        run: |
          flit publish
        env:
          FLIT_USERNAME: __token__
          FLIT_PASSWORD: ${{ secrets.PYPI_KEY }}
